server:
  port: 8080

spring:
  application:
    name: springmind-wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/springmind
    username: springmind
    password: springmind
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
